version: '3.8'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "80:8080"
    volumes:
      - .:/home/node/app
    depends_on:
      - redis

  redis:
    image: redis:6.2.3-alpine
    ports:
      - "6379:6379"